Update monitor and scheduler to use cache setup in api
buildkite/agent-stack-k8s pull request #42
Opened 2022-12-20 20:57 UTC by jmcshane

Still working on setting up local runner, unit tests are working will need to validate with integration tests as well.

2022-12-22 16:25 UTC, benmoss requested changes

2022-12-22 20:08 UTC, jmcshane commented on api/kubernetes.go
> +package api
yeah, im going to create a `kubernetes` package

2022-12-22 20:08 UTC, jmcshane commented on main.go
> +var maxInFlight *int32 = flag.Int32("max-in-flight", 1, "max jobs in flight, 0 means no max")
:+1:

2022-12-22 20:10 UTC, jmcshane commented on main.go
> +	clientConfig := restconfig.GetConfigOrDie()
im confused...it says that it tries four files here including the HOME/.kube/config: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/config#GetConfigOrDie

2022-12-22 20:10 UTC, jmcshane commented on api/kubernetes.go
> +func NewBuildkiteJobManagerOrDie(ctx context.Context, clientset kubernetes.Interface, tags ...string) *BuildkiteJobManager {
ill update this

2023-01-04 13:21 UTC, jmcshane commented
@benmoss updated with your PR

2023-01-04 15:00 UTC, benmoss approved these changes

2023-01-04 15:02 UTC, merged